// Category Data
export const categoryData = {
  "coconut-oil": {
    name: "Coconut Oil",
    description: "Premium virgin and organic coconut oil varieties sourced from the finest coconuts",
    detailedDescription:
      "Our coconut oil collection features the highest quality virgin and extra virgin coconut oils, cold-pressed to retain maximum nutritional value. Sourced from organic coconut farms across Kerala and Tamil Nadu, each bottle represents purity and traditional processing methods passed down through generations.",
    image:
      "https://image.pollinations.ai/prompt/coconut%20oil%20bottles%20organic%20premium%20natural%20lighting?width=600&height=400",
    heroImage:
      "https://image.pollinations.ai/prompt/coconut%20palm%20trees%20organic%20farm%20coconut%20oil%20production%20natural?width=1920&height=800",
    productCount: 12,
    priceRange: "₹449 - ₹1,899",
    avgRating: 4.8,
    highlights: ["Cold-Pressed", "Virgin Quality", "Chemical-Free", "Traditional Methods"],
    benefits: [
      "Rich in medium-chain triglycerides (MCTs) for quick energy",
      "Contains lauric acid with antimicrobial properties",
      "Supports heart health and weight management",
      "Excellent for cooking, skincare, and hair care",
      "High smoke point suitable for all cooking methods",
    ],
    qualityStandards: [
      "100% organic certified coconuts",
      "Cold-pressed within 24 hours of harvesting",
      "No chemical processing or additives",
      "Third-party tested for purity",
      "Stored in food-grade containers",
    ],
  },
  "pure-honey": {
    name: "Pure Honey",
    description: "Raw, unprocessed honey from natural sources across India's pristine forests",
    detailedDescription:
      "Our honey collection showcases the diverse floral landscapes of India, from the dense forests of the Western Ghats to the wildflower meadows of Himachal Pradesh. Each variety is raw, unfiltered, and unpasteurized, preserving the natural enzymes, antioxidants, and unique flavor profiles that make Indian honey exceptional.",
    image:
      "https://image.pollinations.ai/prompt/pure%20honey%20jars%20golden%20natural%20organic%20beehive?width=600&height=400",
    heroImage:
      "https://image.pollinations.ai/prompt/beehives%20natural%20forest%20honey%20collection%20organic%20beekeeping?width=1920&height=800",
    productCount: 15,
    priceRange: "₹349 - ₹1,299",
    avgRating: 4.9,
    highlights: ["Raw & Unfiltered", "Single-Origin", "Enzyme-Rich", "No Additives"],
    benefits: [
      "Natural source of antioxidants and enzymes",
      "Supports immune system and digestive health",
      "Natural energy booster with sustained release",
      "Anti-inflammatory and antimicrobial properties",
      "Helps soothe throat and respiratory issues",
    ],
    qualityStandards: [
      "Raw and unprocessed honey",
      "No heating above 40°C to preserve enzymes",
      "Regular testing for purity and authenticity",
      "Sustainable beekeeping practices",
      "Traceability to specific apiaries",
    ],
  },
  "pulses-lentils": {
    name: "Pulses & Lentils",
    description: "Premium organic pulses and lentils rich in protein and essential nutrients",
    detailedDescription:
      "Our pulse and lentil collection represents the finest organic legumes from across India's agricultural heartlands. From the black gram fields of Punjab to the red lentil farms of Rajasthan, each variety is carefully selected for size, color, and nutritional density. These protein powerhouses are essential for a balanced vegetarian diet.",
    image:
      "https://image.pollinations.ai/prompt/mixed%20pulses%20variety%20colorful%20organic%20lentils%20natural?width=600&height=400",
    heroImage:
      "https://image.pollinations.ai/prompt/organic%20pulse%20farm%20lentils%20harvest%20natural%20agriculture?width=1920&height=800",
    productCount: 18,
    priceRange: "₹199 - ₹599",
    avgRating: 4.7,
    highlights: ["High Protein", "Organic Certified", "Farm Fresh", "Multiple Varieties"],
    benefits: [
      "Excellent source of plant-based protein",
      "Rich in dietary fiber for digestive health",
      "Low glycemic index helps regulate blood sugar",
      "Contains essential minerals like iron and folate",
      "Supports heart health and weight management",
    ],
    qualityStandards: [
      "100% organic cultivation without pesticides",
      "Proper cleaning and sorting processes",
      "Moisture content maintained below 12%",
      "Regular testing for aflatoxins and contaminants",
      "Vacuum-packed for freshness",
    ],
  },
  "spices-herbs": {
    name: "Spices & Herbs",
    description: "Aromatic organic spices and herbs that bring authentic flavors to your kitchen",
    detailedDescription:
      "Our spice collection celebrates India's rich culinary heritage with premium organic spices sourced from their native regions. From Kerala's cardamom hills to Kashmir's saffron fields, each spice is harvested at peak potency and processed using traditional methods to preserve essential oils and flavor compounds.",
    image:
      "https://image.pollinations.ai/prompt/organic%20spices%20herbs%20colorful%20natural%20aromatic?width=600&height=400",
    heroImage:
      "https://image.pollinations.ai/prompt/spice%20plantation%20organic%20herbs%20natural%20farming%20aromatic?width=1920&height=800",
    productCount: 25,
    priceRange: "₹99 - ₹2,499",
    avgRating: 4.8,
    highlights: ["Single-Origin", "Sun-Dried", "Aromatic", "Pesticide-Free"],
    benefits: [
      "Rich in antioxidants and essential oils",
      "Natural anti-inflammatory properties",
      "Supports digestion and metabolism",
      "Enhances flavor without artificial additives",
      "Traditional medicinal properties",
    ],
    qualityStandards: [
      "Organic certification from source farms",
      "Sun-dried to preserve natural oils",
      "Ground in small batches for freshness",
      "No artificial colors or preservatives",
      "Proper storage to maintain potency",
    ],
  },
  "organic-grains": {
    name: "Organic Grains",
    description: "Wholesome organic grains and cereals for healthy, nutritious meals",
    detailedDescription:
      "Our grain collection features ancient and modern varieties cultivated using sustainable organic farming practices. From traditional millets that sustained our ancestors to heritage rice varieties, each grain is carefully processed to retain maximum nutritional value while ensuring food safety and quality.",
    image:
      "https://image.pollinations.ai/prompt/organic%20grains%20cereals%20natural%20wholesome%20healthy?width=600&height=400",
    heroImage:
      "https://image.pollinations.ai/prompt/organic%20grain%20fields%20natural%20farming%20sustainable%20agriculture?width=1920&height=800",
    productCount: 20,
    priceRange: "₹149 - ₹899",
    avgRating: 4.6,
    highlights: ["Ancient Varieties", "Whole Grains", "Gluten-Free Options", "Nutrient-Dense"],
    benefits: [
      "High in dietary fiber and complex carbohydrates",
      "Rich in B-vitamins and essential minerals",
      "Supports sustained energy release",
      "Gluten-free options available",
      "Promotes digestive health",
    ],
    qualityStandards: [
      "Certified organic cultivation",
      "Minimal processing to retain nutrients",
      "Regular testing for heavy metals",
      "Proper cleaning and grading",
      "Moisture-controlled storage",
    ],
  },
  "dry-fruits-nuts": {
    name: "Dry Fruits & Nuts",
    description: "Premium quality dry fruits and nuts packed with natural goodness",
    detailedDescription:
      "Our dry fruits and nuts collection features the finest quality produce from India's premier growing regions. From Kashmir's walnuts to California's almonds, each variety is carefully selected, processed, and packed to preserve freshness and nutritional value. These nutrient-dense snacks are perfect for healthy living.",
    image:
      "https://image.pollinations.ai/prompt/premium%20dry%20fruits%20nuts%20natural%20healthy%20organic?width=600&height=400",
    heroImage:
      "https://image.pollinations.ai/prompt/dry%20fruits%20nuts%20orchard%20natural%20harvest%20premium?width=1920&height=800",
    productCount: 22,
    priceRange: "₹299 - ₹1,999",
    avgRating: 4.7,
    highlights: ["Premium Grade", "Natural Processing", "Nutrient-Rich", "Fresh Harvest"],
    benefits: [
      "Rich in healthy fats and proteins",
      "High in vitamins E and B-complex",
      "Contains essential minerals like magnesium",
      "Supports heart and brain health",
      "Natural source of energy",
    ],
    qualityStandards: [
      "Grade A quality selection",
      "Natural drying without chemicals",
      "Regular quality checks for freshness",
      "Proper packaging to prevent rancidity",
      "Temperature-controlled storage",
    ],
  },
}

// Extended Products Data
export const products = [
  // Coconut Oil Products (12 products)
  {
    id: 1,
    name: "Premium Virgin Coconut Oil",
    category: "Coconut Oil",
    price: "₹899",
    originalPrice: "₹1,199",
    image:
      "https://image.pollinations.ai/prompt/premium%20virgin%20coconut%20oil%20glass%20jar%20organic?width=400&height=400",
    rating: 4.9,
    reviews: 156,
    badge: "Best Seller",
    description: "Cold-pressed virgin coconut oil with natural aroma and taste",
    inStock: true,
    weight: "500ml",
    features: ["Cold-Pressed", "Virgin Quality", "Chemical-Free"],
    discount: 25,
  },
  {
    id: 2,
    name: "Organic Extra Virgin Coconut Oil",
    category: "Coconut Oil",
    price: "₹1,299",
    originalPrice: "₹1,599",
    image:
      "https://image.pollinations.ai/prompt/organic%20extra%20virgin%20coconut%20oil%20premium%20packaging?width=400&height=400",
    rating: 4.8,
    reviews: 89,
    badge: "Premium",
    description: "Highest grade organic coconut oil for cooking and wellness",
    inStock: true,
    weight: "1L",
    features: ["Extra Virgin", "Organic Certified", "Multi-Purpose"],
  },
  {
    id: 3,
    name: "Cold-Pressed Coconut Oil",
    category: "Coconut Oil",
    price: "₹749",
    originalPrice: "₹999",
    image:
      "https://image.pollinations.ai/prompt/cold%20pressed%20coconut%20oil%20natural%20bottle?width=400&height=400",
    rating: 4.7,
    reviews: 134,
    badge: "Popular",
    description: "Traditional cold-pressed method preserving natural nutrients",
    inStock: true,
    weight: "500ml",
    features: ["Traditional Method", "Nutrient-Rich", "Pure"],
  },
  {
    id: 4,
    name: "Coconut Oil for Hair & Skin",
    category: "Coconut Oil",
    price: "₹649",
    originalPrice: "₹849",
    image:
      "https://image.pollinations.ai/prompt/coconut%20oil%20hair%20skin%20care%20natural%20beauty?width=400&height=400",
    rating: 4.6,
    reviews: 203,
    badge: "Beauty",
    description: "Specially processed coconut oil for hair and skincare",
    inStock: true,
    weight: "250ml",
    features: ["Beauty Grade", "Moisturizing", "Natural"],
  },
  {
    id: 5,
    name: "Organic Coconut Oil - Family Pack",
    category: "Coconut Oil",
    price: "₹1,899",
    originalPrice: "₹2,399",
    image:
      "https://image.pollinations.ai/prompt/organic%20coconut%20oil%20family%20pack%20large%20container?width=400&height=400",
    rating: 4.8,
    reviews: 67,
    badge: "Value Pack",
    description: "Large family pack of premium organic coconut oil",
    inStock: true,
    weight: "2L",
    features: ["Family Size", "Economic", "Premium Quality"],
    discount: 20,
  },
  {
    id: 6,
    name: "Virgin Coconut Oil - Travel Size",
    category: "Coconut Oil",
    price: "₹449",
    originalPrice: "₹599",
    image:
      "https://image.pollinations.ai/prompt/virgin%20coconut%20oil%20travel%20size%20small%20bottle?width=400&height=400",
    rating: 4.5,
    reviews: 92,
    badge: "Travel",
    description: "Convenient travel-sized virgin coconut oil",
    inStock: true,
    weight: "200ml",
    features: ["Travel Size", "Convenient", "Pure"],
  },
  {
    id: 7,
    name: "Coconut Oil with Herbs",
    category: "Coconut Oil",
    price: "₹799",
    originalPrice: "₹1,099",
    image: "https://image.pollinations.ai/prompt/coconut%20oil%20with%20herbs%20natural%20infused?width=400&height=400",
    rating: 4.7,
    reviews: 78,
    badge: "Herbal",
    description: "Virgin coconut oil infused with traditional herbs",
    inStock: true,
    weight: "500ml",
    features: ["Herb-Infused", "Traditional", "Therapeutic"],
  },
  {
    id: 8,
    name: "Raw Coconut Oil - Unrefined",
    category: "Coconut Oil",
    price: "₹949",
    originalPrice: "₹1,249",
    image: "https://image.pollinations.ai/prompt/raw%20coconut%20oil%20unrefined%20natural%20pure?width=400&height=400",
    rating: 4.9,
    reviews: 145,
    badge: "Raw",
    description: "Completely unrefined raw coconut oil with natural coconut aroma",
    inStock: true,
    weight: "750ml",
    features: ["Unrefined", "Raw", "Natural Aroma"],
  },
  {
    id: 9,
    name: "Coconut Oil - Cooking Grade",
    category: "Coconut Oil",
    price: "₹699",
    originalPrice: "₹899",
    image:
      "https://image.pollinations.ai/prompt/coconut%20oil%20cooking%20grade%20kitchen%20culinary?width=400&height=400",
    rating: 4.6,
    reviews: 189,
    badge: "Cooking",
    description: "High-quality coconut oil perfect for all cooking needs",
    inStock: true,
    weight: "1L",
    features: ["High Smoke Point", "Cooking Grade", "Versatile"],
  },
  {
    id: 10,
    name: "Organic Baby Coconut Oil",
    category: "Coconut Oil",
    price: "₹549",
    originalPrice: "₹749",
    image: "https://image.pollinations.ai/prompt/organic%20baby%20coconut%20oil%20gentle%20pure?width=400&height=400",
    rating: 4.8,
    reviews: 234,
    badge: "Baby Care",
    description: "Gentle organic coconut oil specially processed for babies",
    inStock: true,
    weight: "200ml",
    features: ["Baby-Safe", "Gentle", "Hypoallergenic"],
  },
  {
    id: 11,
    name: "Coconut Oil with Vitamin E",
    category: "Coconut Oil",
    price: "₹849",
    originalPrice: "₹1,149",
    image: "https://image.pollinations.ai/prompt/coconut%20oil%20vitamin%20e%20enriched%20premium?width=400&height=400",
    rating: 4.7,
    reviews: 98,
    badge: "Enriched",
    description: "Virgin coconut oil enriched with natural Vitamin E",
    inStock: false,
    weight: "500ml",
    features: ["Vitamin E", "Antioxidant", "Premium"],
  },
  {
    id: 12,
    name: "Artisanal Coconut Oil",
    category: "Coconut Oil",
    price: "₹1,199",
    originalPrice: "₹1,499",
    image:
      "https://image.pollinations.ai/prompt/artisanal%20coconut%20oil%20handcrafted%20premium%20quality?width=400&height=400",
    rating: 4.9,
    reviews: 56,
    badge: "Artisanal",
    description: "Handcrafted coconut oil made using traditional methods",
    inStock: true,
    weight: "500ml",
    features: ["Handcrafted", "Traditional", "Small Batch"],
  },

  // Pure Honey Products (15 products)
  {
    id: 13,
    name: "Raw Forest Honey",
    category: "Pure Honey",
    price: "₹649",
    originalPrice: "₹799",
    image:
      "https://image.pollinations.ai/prompt/raw%20forest%20honey%20glass%20jar%20golden%20natural?width=400&height=400",
    rating: 4.9,
    reviews: 203,
    badge: "Best Seller",
    description: "Unprocessed raw honey directly from forest beehives",
    inStock: true,
    weight: "500g",
    features: ["Raw", "Unfiltered", "Forest Source"],
    discount: 18,
  },
  {
    id: 14,
    name: "Wildflower Honey",
    category: "Pure Honey",
    price: "₹549",
    originalPrice: "₹699",
    image:
      "https://image.pollinations.ai/prompt/wildflower%20honey%20jar%20colorful%20natural%20organic?width=400&height=400",
    rating: 4.8,
    reviews: 167,
    badge: "Premium",
    description: "Multi-floral honey with rich taste and aroma",
    inStock: true,
    weight: "500g",
    features: ["Multi-Floral", "Rich Taste", "Natural"],
  },
  {
    id: 15,
    name: "Acacia Honey",
    category: "Pure Honey",
    price: "₹799",
    originalPrice: "₹999",
    image: "https://image.pollinations.ai/prompt/acacia%20honey%20light%20golden%20premium%20jar?width=400&height=400",
    rating: 4.7,
    reviews: 92,
    badge: "Rare",
    description: "Light, delicate honey from acacia flowers",
    inStock: false,
    weight: "500g",
    features: ["Single-Origin", "Delicate", "Light Color"],
  },
  {
    id: 16,
    name: "Himalayan Honey",
    category: "Pure Honey",
    price: "₹899",
    originalPrice: "₹1,199",
    image:
      "https://image.pollinations.ai/prompt/himalayan%20honey%20mountain%20pure%20natural%20premium?width=400&height=400",
    rating: 4.9,
    reviews: 134,
    badge: "Mountain",
    description: "Pure honey from the pristine Himalayan mountains",
    inStock: true,
    weight: "500g",
    features: ["High Altitude", "Pure", "Medicinal"],
  },
  {
    id: 17,
    name: "Manuka Honey",
    category: "Pure Honey",
    price: "₹1,299",
    originalPrice: "₹1,699",
    image: "https://image.pollinations.ai/prompt/manuka%20honey%20premium%20medicinal%20natural?width=400&height=400",
    rating: 4.8,
    reviews: 78,
    badge: "Medicinal",
    description: "Premium Manuka honey with high antibacterial activity",
    inStock: true,
    weight: "250g",
    features: ["Antibacterial", "Medicinal", "Premium"],
    discount: 23,
  },
  {
    id: 18,
    name: "Eucalyptus Honey",
    category: "Pure Honey",
    price: "₹599",
    originalPrice: "₹749",
    image:
      "https://image.pollinations.ai/prompt/eucalyptus%20honey%20natural%20therapeutic%20organic?width=400&height=400",
    rating: 4.6,
    reviews: 156,
    badge: "Therapeutic",
    description: "Honey from eucalyptus flowers with therapeutic properties",
    inStock: true,
    weight: "500g",
    features: ["Therapeutic", "Respiratory Health", "Natural"],
  },
  {
    id: 19,
    name: "Clover Honey",
    category: "Pure Honey",
    price: "₹449",
    originalPrice: "₹599",
    image:
      "https://image.pollinations.ai/prompt/clover%20honey%20mild%20sweet%20natural%20organic?width=400&height=400",
    rating: 4.5,
    reviews: 189,
    badge: "Mild",
    description: "Mild and sweet honey from clover blossoms",
    inStock: true,
    weight: "500g",
    features: ["Mild Taste", "Sweet", "Light Color"],
  },
  {
    id: 20,
    name: "Sunflower Honey",
    category: "Pure Honey",
    price: "₹519",
    originalPrice: "₹679",
    image:
      "https://image.pollinations.ai/prompt/sunflower%20honey%20bright%20golden%20natural%20pure?width=400&height=400",
    rating: 4.7,
    reviews: 123,
    badge: "Golden",
    description: "Bright golden honey from sunflower fields",
    inStock: true,
    weight: "500g",
    features: ["Golden Color", "Rich Flavor", "Natural"],
  },
  {
    id: 21,
    name: "Lychee Honey",
    category: "Pure Honey",
    price: "₹749",
    originalPrice: "₹949",
    image:
      "https://image.pollinations.ai/prompt/lychee%20honey%20exotic%20floral%20premium%20natural?width=400&height=400",
    rating: 4.8,
    reviews: 87,
    badge: "Exotic",
    description: "Exotic honey with delicate lychee floral notes",
    inStock: true,
    weight: "500g",
    features: ["Exotic", "Floral Notes", "Premium"],
  },
  {
    id: 22,
    name: "Jamun Honey",
    category: "Pure Honey",
    price: "₹699",
    originalPrice: "₹899",
    image:
      "https://image.pollinations.ai/prompt/jamun%20honey%20dark%20rich%20natural%20medicinal?width=400&height=400",
    rating: 4.6,
    reviews: 145,
    badge: "Dark",
    description: "Dark, rich honey from jamun (black plum) flowers",
    inStock: true,
    weight: "500g",
    features: ["Dark Color", "Rich Taste", "Antioxidant"],
  },
  {
    id: 23,
    name: "Neem Honey",
    category: "Pure Honey",
    price: "₹849",
    originalPrice: "₹1,099",
    image: "https://image.pollinations.ai/prompt/neem%20honey%20medicinal%20natural%20therapeutic?width=400&height=400",
    rating: 4.7,
    reviews: 98,
    badge: "Medicinal",
    description: "Medicinal honey from neem flowers with healing properties",
    inStock: true,
    weight: "500g",
    features: ["Medicinal", "Healing", "Bitter-Sweet"],
  },
  {
    id: 24,
    name: "Tulsi Honey",
    category: "Pure Honey",
    price: "₹649",
    originalPrice: "₹849",
    image: "https://image.pollinations.ai/prompt/tulsi%20honey%20holy%20basil%20natural%20sacred?width=400&height=400",
    rating: 4.8,
    reviews: 167,
    badge: "Sacred",
    description: "Sacred honey from tulsi (holy basil) flowers",
    inStock: true,
    weight: "500g",
    features: ["Sacred", "Immunity Boost", "Aromatic"],
  },
  {
    id: 25,
    name: "Mustard Honey",
    category: "Pure Honey",
    price: "₹499",
    originalPrice: "₹649",
    image:
      "https://image.pollinations.ai/prompt/mustard%20honey%20yellow%20natural%20organic%20pure?width=400&height=400",
    rating: 4.5,
    reviews: 134,
    badge: "Regional",
    description: "Regional honey from mustard flower fields",
    inStock: true,
    weight: "500g",
    features: ["Regional", "Distinctive", "Natural"],
  },
  {
    id: 26,
    name: "Honey Comb - Raw",
    category: "Pure Honey",
    price: "₹949",
    originalPrice: "₹1,249",
    image:
      "https://image.pollinations.ai/prompt/raw%20honey%20comb%20natural%20wax%20pure%20organic?width=400&height=400",
    rating: 4.9,
    reviews: 76,
    badge: "Raw Comb",
    description: "Natural honeycomb with raw honey and beeswax",
    inStock: true,
    weight: "400g",
    features: ["Raw Comb", "Natural Wax", "Pure"],
    discount: 24,
  },
  {
    id: 27,
    name: "Honey Gift Set",
    category: "Pure Honey",
    price: "₹1,199",
    originalPrice: "₹1,599",
    image:
      "https://image.pollinations.ai/prompt/honey%20gift%20set%20variety%20pack%20premium%20collection?width=400&height=400",
    rating: 4.8,
    reviews: 89,
    badge: "Gift Set",
    description: "Premium gift set with 4 different honey varieties",
    inStock: true,
    weight: "4x250g",
    features: ["Variety Pack", "Gift Box", "Premium"],
  },

  // Pulses & Lentils Products (18 products)
  {
    id: 28,
    name: "Organic Mungbean (Green Gram)",
    category: "Pulses & Lentils",
    price: "₹299",
    originalPrice: "₹399",
    image:
      "https://image.pollinations.ai/prompt/organic%20mungbean%20green%20gram%20natural%20packaging?width=400&height=400",
    rating: 4.6,
    reviews: 78,
    badge: "Healthy",
    description: "High-protein organic green gram perfect for sprouting",
    inStock: true,
    weight: "1kg",
    features: ["High Protein", "Sprouting", "Organic"],
    discount: 25,
  },
  {
    id: 29,
    name: "Premium Chickpea (Garbanzo)",
    category: "Pulses & Lentils",
    price: "₹349",
    originalPrice: "₹449",
    image: "https://image.pollinations.ai/prompt/premium%20chickpea%20garbanzo%20beans%20organic?width=400&height=400",
    rating: 4.7,
    reviews: 156,
    badge: "Popular",
    description: "Large, premium quality organic chickpeas",
    inStock: true,
    weight: "1kg",
    features: ["Large Size", "Premium", "Versatile"],
  },
  {
    id: 30,
    name: "Organic Masoor (Red Lentils)",
    category: "Pulses & Lentils",
    price: "₹249",
    originalPrice: "₹329",
    image:
      "https://image.pollinations.ai/prompt/organic%20masoor%20red%20lentils%20natural%20bowl?width=400&height=400",
    rating: 4.5,
    reviews: 89,
    badge: "Nutritious",
    description: "Rich in protein and fiber, perfect for daily cooking",
    inStock: true,
    weight: "1kg",
    features: ["High Fiber", "Quick Cooking", "Nutritious"],
  },
  {
    id: 31,
    name: "Split Moongdal (Green Gram)",
    category: "Pulses & Lentils",
    price: "₹329",
    originalPrice: "₹429",
    image:
      "https://image.pollinations.ai/prompt/split%20moongdal%20green%20gram%20organic%20lentils?width=400&height=400",
    rating: 4.6,
    reviews: 67,
    badge: "Traditional",
    description: "Split green gram dal, easy to cook and digest",
    inStock: true,
    weight: "1kg",
    features: ["Easy Digest", "Traditional", "Split"],
  },
  {
    id: 32,
    name: "Mixed Pulse Varieties",
    category: "Pulses & Lentils",
    price: "₹399",
    originalPrice: "₹529",
    image:
      "https://image.pollinations.ai/prompt/mixed%20pulse%20varieties%20colorful%20organic%20blend?width=400&height=400",
    rating: 4.8,
    reviews: 134,
    badge: "Combo",
    description: "Nutritious mix of premium organic pulses and lentils",
    inStock: true,
    weight: "1kg",
    features: ["Mixed Variety", "Nutritious", "Balanced"],
    discount: 24,
  },
  {
    id: 33,
    name: "Black Gram (Urad Dal)",
    category: "Pulses & Lentils",
    price: "₹379",
    originalPrice: "₹479",
    image: "https://image.pollinations.ai/prompt/black%20gram%20urad%20dal%20organic%20natural?width=400&height=400",
    rating: 4.7,
    reviews: 123,
    badge: "Premium",
    description: "Premium quality black gram for traditional recipes",
    inStock: true,
    weight: "1kg",
    features: ["Premium Quality", "Traditional", "Rich Protein"],
  },
  {
    id: 34,
    name: "Toor Dal (Pigeon Pea)",
    category: "Pulses & Lentils",
    price: "₹319",
    originalPrice: "₹419",
    image: "https://image.pollinations.ai/prompt/toor%20dal%20pigeon%20pea%20organic%20yellow?width=400&height=400",
    rating: 4.6,
    reviews: 178,
    badge: "Staple",
    description: "Essential yellow lentil for everyday Indian cooking",
    inStock: true,
    weight: "1kg",
    features: ["Staple Food", "Yellow Dal", "Essential"],
  },
  {
    id: 35,
    name: "Chana Dal (Split Chickpea)",
    category: "Pulses & Lentils",
    price: "₹289",
    originalPrice: "₹379",
    image:
      "https://image.pollinations.ai/prompt/chana%20dal%20split%20chickpea%20organic%20natural?width=400&height=400",
    rating: 4.5,
    reviews: 145,
    badge: "Popular",
    description: "Split chickpea dal with rich taste and nutrition",
    inStock: true,
    weight: "1kg",
    features: ["Rich Taste", "Split", "Nutritious"],
  },
  {
    id: 36,
    name: "Kidney Beans (Rajma)",
    category: "Pulses & Lentils",
    price: "₹359",
    originalPrice: "₹459",
    image: "https://image.pollinations.ai/prompt/kidney%20beans%20rajma%20organic%20red%20natural?width=400&height=400",
    rating: 4.7,
    reviews: 167,
    badge: "Protein Rich",
    description: "Premium red kidney beans rich in protein and fiber",
    inStock: true,
    weight: "1kg",
    features: ["High Protein", "Fiber Rich", "Premium"],
  },
  {
    id: 37,
    name: "Black Eyed Peas (Lobia)",
    category: "Pulses & Lentils",
    price: "₹279",
    originalPrice: "₹369",
    image: "https://image.pollinations.ai/prompt/black%20eyed%20peas%20lobia%20organic%20natural?width=400&height=400",
    rating: 4.4,
    reviews: 98,
    badge: "Healthy",
    description: "Nutritious black-eyed peas for healthy meals",
    inStock: true,
    weight: "1kg",
    features: ["Nutritious", "Healthy", "Versatile"],
  },
  {
    id: 38,
    name: "Horse Gram (Kulthi)",
    category: "Pulses & Lentils",
    price: "₹259",
    originalPrice: "₹339",
    image:
      "https://image.pollinations.ai/prompt/horse%20gram%20kulthi%20organic%20traditional%20pulse?width=400&height=400",
    rating: 4.6,
    reviews: 76,
    badge: "Traditional",
    description: "Traditional horse gram with medicinal properties",
    inStock: true,
    weight: "1kg",
    features: ["Medicinal", "Traditional", "Therapeutic"],
  },
  {
    id: 39,
    name: "Field Peas (Matar)",
    category: "Pulses & Lentils",
    price: "₹299",
    originalPrice: "₹389",
    image: "https://image.pollinations.ai/prompt/field%20peas%20matar%20organic%20green%20natural?width=400&height=400",
    rating: 4.5,
    reviews: 134,
    badge: "Fresh",
    description: "Fresh organic field peas for curries and snacks",
    inStock: true,
    weight: "1kg",
    features: ["Fresh", "Versatile", "Natural"],
  },
  {
    id: 40,
    name: "Lima Beans",
    category: "Pulses & Lentils",
    price: "₹389",
    originalPrice: "₹499",
    image: "https://image.pollinations.ai/prompt/lima%20beans%20organic%20large%20white%20premium?width=400&height=400",
    rating: 4.6,
    reviews: 89,
    badge: "Premium",
    description: "Large, creamy lima beans with delicate flavor",
    inStock: true,
    weight: "1kg",
    features: ["Large Size", "Creamy", "Delicate"],
  },
  {
    id: 41,
    name: "Navy Beans",
    category: "Pulses & Lentils",
    price: "₹349",
    originalPrice: "₹449",
    image: "https://image.pollinations.ai/prompt/navy%20beans%20organic%20small%20white%20natural?width=400&height=400",
    rating: 4.5,
    reviews: 112,
    badge: "Versatile",
    description: "Small white navy beans perfect for soups and stews",
    inStock: true,
    weight: "1kg",
    features: ["Small Size", "Versatile", "Soup Perfect"],
  },
  {
    id: 42,
    name: "Pinto Beans",
    category: "Pulses & Lentils",
    price: "₹329",
    originalPrice: "₹429",
    image: "https://image.pollinations.ai/prompt/pinto%20beans%20organic%20speckled%20natural?width=400&height=400",
    rating: 4.4,
    reviews: 87,
    badge: "Colorful",
    description: "Speckled pinto beans with rich, earthy flavor",
    inStock: false,
    weight: "1kg",
    features: ["Speckled", "Earthy Flavor", "Rich"],
  },
  {
    id: 43,
    name: "Pulse Flour Mix",
    category: "Pulses & Lentils",
    price: "₹199",
    originalPrice: "₹259",
    image: "https://image.pollinations.ai/prompt/pulse%20flour%20mix%20organic%20ground%20natural?width=400&height=400",
    rating: 4.7,
    reviews: 156,
    badge: "Ground",
    description: "Ground pulse flour mix for healthy cooking",
    inStock: true,
    weight: "500g",
    features: ["Ground", "Healthy", "Ready-to-Use"],
  },
  {
    id: 44,
    name: "Sprouting Mix",
    category: "Pulses & Lentils",
    price: "₹279",
    originalPrice: "₹359",
    image:
      "https://image.pollinations.ai/prompt/sprouting%20mix%20organic%20seeds%20healthy%20natural?width=400&height=400",
    rating: 4.8,
    reviews: 203,
    badge: "Sprouting",
    description: "Special mix of pulses perfect for sprouting",
    inStock: true,
    weight: "1kg",
    features: ["Sprouting", "Healthy", "Mixed Seeds"],
    discount: 22,
  },
  {
    id: 45,
    name: "Pulse Gift Hamper",
    category: "Pulses & Lentils",
    price: "₹599",
    originalPrice: "₹799",
    image: "https://image.pollinations.ai/prompt/pulse%20gift%20hamper%20variety%20pack%20organic?width=400&height=400",
    rating: 4.6,
    reviews: 67,
    badge: "Gift Set",
    description: "Variety pack of 6 different organic pulses",
    inStock: true,
    weight: "6x500g",
    features: ["Variety Pack", "Gift Box", "Assorted"],
  },

  // Spices & Herbs Products (25 products)
  {
    id: 46,
    name: "Organic Turmeric Powder",
    category: "Spices & Herbs",
    price: "₹199",
    originalPrice: "₹249",
    image:
      "https://image.pollinations.ai/prompt/organic%20turmeric%20powder%20golden%20spice%20natural?width=400&height=400",
    rating: 4.8,
    reviews: 234,
    badge: "Anti-inflammatory",
    description: "Pure organic turmeric powder with high curcumin content",
    inStock: true,
    weight: "250g",
    features: ["High Curcumin", "Anti-inflammatory", "Pure"],
    discount: 20,
  },
  {
    id: 47,
    name: "Cardamom Pods - Green",
    category: "Spices & Herbs",
    price: "₹899",
    originalPrice: "₹1,199",
    image:
      "https://image.pollinations.ai/prompt/green%20cardamom%20pods%20organic%20aromatic%20spice?width=400&height=400",
    rating: 4.9,
    reviews: 156,
    badge: "Premium",
    description: "Aromatic green cardamom pods from Kerala hills",
    inStock: true,
    weight: "100g",
    features: ["Aromatic", "Kerala Origin", "Premium"],
  },
  {
    id: 48,
    name: "Cinnamon Sticks - Ceylon",
    category: "Spices & Herbs",
    price: "₹349",
    originalPrice: "₹449",
    image:
      "https://image.pollinations.ai/prompt/ceylon%20cinnamon%20sticks%20organic%20natural%20spice?width=400&height=400",
    rating: 4.7,
    reviews: 189,
    badge: "Ceylon",
    description: "Authentic Ceylon cinnamon sticks with sweet aroma",
    inStock: true,
    weight: "100g",
    features: ["Ceylon Grade", "Sweet Aroma", "Authentic"],
  },
  {
    id: 49,
    name: "Black Pepper Whole",
    category: "Spices & Herbs",
    price: "₹449",
    originalPrice: "₹599",
    image:
      "https://image.pollinations.ai/prompt/black%20pepper%20whole%20organic%20spice%20natural?width=400&height=400",
    rating: 4.6,
    reviews: 167,
    badge: "King of Spices",
    description: "Premium whole black pepper with intense flavor",
    inStock: true,
    weight: "200g",
    features: ["Whole", "Intense Flavor", "Premium"],
  },
  {
    id: 50,
    name: "Cumin Seeds",
    category: "Spices & Herbs",
    price: "₹179",
    originalPrice: "₹229",
    image:
      "https://image.pollinations.ai/prompt/cumin%20seeds%20organic%20natural%20spice%20aromatic?width=400&height=400",
    rating: 4.5,
    reviews: 203,
    badge: "Essential",
    description: "Aromatic cumin seeds for authentic Indian cooking",
    inStock: true,
    weight: "250g",
    features: ["Aromatic", "Essential", "Indian"],
  },
  {
    id: 51,
    name: "Red Chili Powder",
    category: "Spices & Herbs",
    price: "₹159",
    originalPrice: "₹199",
    image: "https://image.pollinations.ai/prompt/red%20chili%20powder%20organic%20spicy%20natural?width=400&height=400",
    rating: 4.6,
    reviews: 178,
    badge: "Spicy",
    description: "Pure red chili powder with perfect heat and color",
    inStock: true,
    weight: "250g",
    features: ["Pure", "Perfect Heat", "Natural Color"],
  },
  {
    id: 52,
    name: "Coriander Seeds",
    category: "Spices & Herbs",
    price: "₹149",
    originalPrice: "₹189",
    image:
      "https://image.pollinations.ai/prompt/coriander%20seeds%20organic%20natural%20spice%20aromatic?width=400&height=400",
    rating: 4.5,
    reviews: 145,
    badge: "Aromatic",
    description: "Fresh coriander seeds with citrusy aroma",
    inStock: true,
    weight: "250g",
    features: ["Fresh", "Citrusy", "Aromatic"],
  },
  {
    id: 53,
    name: "Garam Masala Powder",
    category: "Spices & Herbs",
    price: "₹249",
    originalPrice: "₹319",
    image:
      "https://image.pollinations.ai/prompt/garam%20masala%20powder%20organic%20blend%20spices?width=400&height=400",
    rating: 4.8,
    reviews: 267,
    badge: "Blend",
    description: "Traditional garam masala blend with authentic taste",
    inStock: true,
    weight: "200g",
    features: ["Traditional", "Authentic", "Blend"],
    discount: 22,
  },
  {
    id: 54,
    name: "Cloves Whole",
    category: "Spices & Herbs",
    price: "₹399",
    originalPrice: "₹519",
    image:
      "https://image.pollinations.ai/prompt/cloves%20whole%20organic%20aromatic%20spice%20natural?width=400&height=400",
    rating: 4.7,
    reviews: 123,
    badge: "Aromatic",
    description: "Premium whole cloves with intense aroma",
    inStock: true,
    weight: "100g",
    features: ["Whole", "Intense Aroma", "Premium"],
  },
  {
    id: 55,
    name: "Bay Leaves",
    category: "Spices & Herbs",
    price: "₹129",
    originalPrice: "₹169",
    image:
      "https://image.pollinations.ai/prompt/bay%20leaves%20organic%20natural%20herb%20aromatic?width=400&height=400",
    rating: 4.4,
    reviews: 98,
    badge: "Herb",
    description: "Dried bay leaves for flavoring curries and rice",
    inStock: true,
    weight: "50g",
    features: ["Dried", "Flavoring", "Natural"],
  },

  // Organic Grains Products (20 products)
  {
    id: 56,
    name: "Organic Brown Rice",
    category: "Organic Grains",
    price: "₹299",
    originalPrice: "₹399",
    image: "https://image.pollinations.ai/prompt/organic%20brown%20rice%20whole%20grain%20natural?width=400&height=400",
    rating: 4.6,
    reviews: 178,
    badge: "Whole Grain",
    description: "Nutritious organic brown rice with natural fiber",
    inStock: true,
    weight: "1kg",
    features: ["Whole Grain", "High Fiber", "Nutritious"],
    discount: 25,
  },
  {
    id: 57,
    name: "Quinoa - White",
    category: "Organic Grains",
    price: "₹549",
    originalPrice: "₹699",
    image:
      "https://image.pollinations.ai/prompt/white%20quinoa%20organic%20superfood%20grain%20natural?width=400&height=400",
    rating: 4.8,
    reviews: 134,
    badge: "Superfood",
    description: "Complete protein superfood quinoa from organic farms",
    inStock: true,
    weight: "500g",
    features: ["Complete Protein", "Superfood", "Gluten-Free"],
  },
  {
    id: 58,
    name: "Finger Millet (Ragi)",
    category: "Organic Grains",
    price: "₹199",
    originalPrice: "₹259",
    image:
      "https://image.pollinations.ai/prompt/finger%20millet%20ragi%20organic%20ancient%20grain?width=400&height=400",
    rating: 4.7,
    reviews: 156,
    badge: "Ancient Grain",
    description: "Calcium-rich finger millet for healthy bones",
    inStock: true,
    weight: "1kg",
    features: ["Calcium Rich", "Ancient Grain", "Healthy"],
  },
  {
    id: 59,
    name: "Pearl Millet (Bajra)",
    category: "Organic Grains",
    price: "₹179",
    originalPrice: "₹229",
    image:
      "https://image.pollinations.ai/prompt/pearl%20millet%20bajra%20organic%20grain%20natural?width=400&height=400",
    rating: 4.5,
    reviews: 123,
    badge: "Gluten-Free",
    description: "Iron-rich pearl millet perfect for rotis and porridge",
    inStock: true,
    weight: "1kg",
    features: ["Iron Rich", "Gluten-Free", "Versatile"],
  },
  {
    id: 60,
    name: "Foxtail Millet",
    category: "Organic Grains",
    price: "₹249",
    originalPrice: "₹319",
    image:
      "https://image.pollinations.ai/prompt/foxtail%20millet%20organic%20small%20grain%20natural?width=400&height=400",
    rating: 4.6,
    reviews: 98,
    badge: "Low GI",
    description: "Low glycemic index foxtail millet for diabetics",
    inStock: true,
    weight: "1kg",
    features: ["Low GI", "Diabetic Friendly", "Small Grain"],
  },
  {
    id: 61,
    name: "Organic Basmati Rice",
    category: "Organic Grains",
    price: "₹449",
    originalPrice: "₹599",
    image:
      "https://image.pollinations.ai/prompt/organic%20basmati%20rice%20premium%20long%20grain?width=400&height=400",
    rating: 4.8,
    reviews: 234,
    badge: "Premium",
    description: "Aromatic organic basmati rice with long grains",
    inStock: true,
    weight: "1kg",
    features: ["Aromatic", "Long Grain", "Premium"],
    discount: 25,
  },
  {
    id: 62,
    name: "Barnyard Millet",
    category: "Organic Grains",
    price: "₹229",
    originalPrice: "₹299",
    image:
      "https://image.pollinations.ai/prompt/barnyard%20millet%20organic%20healthy%20grain%20natural?width=400&height=400",
    rating: 4.5,
    reviews: 87,
    badge: "Healthy",
    description: "Nutritious barnyard millet with high fiber content",
    inStock: true,
    weight: "1kg",
    features: ["High Fiber", "Nutritious", "Healthy"],
  },
  {
    id: 63,
    name: "Little Millet",
    category: "Organic Grains",
    price: "₹219",
    originalPrice: "₹279",
    image:
      "https://image.pollinations.ai/prompt/little%20millet%20organic%20small%20grain%20natural?width=400&height=400",
    rating: 4.4,
    reviews: 76,
    badge: "Small Grain",
    description: "Tiny nutritious millet with great health benefits",
    inStock: true,
    weight: "1kg",
    features: ["Tiny", "Nutritious", "Health Benefits"],
  },
  {
    id: 64,
    name: "Kodo Millet",
    category: "Organic Grains",
    price: "₹239",
    originalPrice: "₹309",
    image:
      "https://image.pollinations.ai/prompt/kodo%20millet%20organic%20ancient%20grain%20healthy?width=400&height=400",
    rating: 4.6,
    reviews: 112,
    badge: "Ancient",
    description: "Ancient kodo millet with antioxidant properties",
    inStock: true,
    weight: "1kg",
    features: ["Ancient", "Antioxidant", "Healthy"],
  },
  {
    id: 65,
    name: "Organic Wheat Flour",
    category: "Organic Grains",
    price: "₹189",
    originalPrice: "₹249",
    image:
      "https://image.pollinations.ai/prompt/organic%20wheat%20flour%20whole%20grain%20natural?width=400&height=400",
    rating: 4.5,
    reviews: 189,
    badge: "Whole Grain",
    description: "Stone-ground organic wheat flour for healthy bread",
    inStock: true,
    weight: "1kg",
    features: ["Stone-Ground", "Whole Grain", "Healthy"],
  },

  // Dry Fruits & Nuts Products (22 products)
  {
    id: 66,
    name: "Premium Almonds",
    category: "Dry Fruits & Nuts",
    price: "₹899",
    originalPrice: "₹1,199",
    image:
      "https://image.pollinations.ai/prompt/premium%20almonds%20natural%20healthy%20nuts%20organic?width=400&height=400",
    rating: 4.8,
    reviews: 267,
    badge: "Premium",
    description: "Premium quality almonds rich in vitamin E and protein",
    inStock: true,
    weight: "500g",
    features: ["Vitamin E", "High Protein", "Premium"],
    discount: 25,
  },
  {
    id: 67,
    name: "Kashmir Walnuts",
    category: "Dry Fruits & Nuts",
    price: "₹1,299",
    originalPrice: "₹1,699",
    image:
      "https://image.pollinations.ai/prompt/kashmir%20walnuts%20premium%20brain%20food%20natural?width=400&height=400",
    rating: 4.9,
    reviews: 189,
    badge: "Kashmir",
    description: "Premium Kashmir walnuts - brain food with omega-3",
    inStock: true,
    weight: "500g",
    features: ["Omega-3", "Brain Food", "Kashmir Origin"],
  },
  {
    id: 68,
    name: "Dates - Medjool",
    category: "Dry Fruits & Nuts",
    price: "₹649",
    originalPrice: "₹849",
    image:
      "https://image.pollinations.ai/prompt/medjool%20dates%20premium%20natural%20sweet%20organic?width=400&height=400",
    rating: 4.7,
    reviews: 234,
    badge: "King of Dates",
    description: "Large, soft Medjool dates - nature's candy",
    inStock: true,
    weight: "500g",
    features: ["Large Size", "Soft", "Natural Sweet"],
  },
  {
    id: 69,
    name: "Cashew Nuts - W320",
    category: "Dry Fruits & Nuts",
    price: "₹1,199",
    originalPrice: "₹1,499",
    image: "https://image.pollinations.ai/prompt/cashew%20nuts%20w320%20premium%20grade%20natural?width=400&height=400",
    rating: 4.8,
    reviews: 156,
    badge: "W320 Grade",
    description: "Premium W320 grade cashews from Kerala",
    inStock: true,
    weight: "500g",
    features: ["W320 Grade", "Kerala Origin", "Premium"],
  },
  {
    id: 70,
    name: "Pistachios - Roasted",
    category: "Dry Fruits & Nuts",
    price: "₹1,599",
    originalPrice: "₹1,999",
    image:
      "https://image.pollinations.ai/prompt/roasted%20pistachios%20premium%20nuts%20healthy%20snack?width=400&height=400",
    rating: 4.6,
    reviews: 123,
    badge: "Roasted",
    description: "Lightly roasted pistachios for healthy snacking",
    inStock: true,
    weight: "500g",
    features: ["Lightly Roasted", "Healthy Snack", "Premium"],
  },
  {
    id: 71,
    name: "Dried Figs (Anjeer)",
    category: "Dry Fruits & Nuts",
    price: "₹799",
    originalPrice: "₹1,049",
    image:
      "https://image.pollinations.ai/prompt/dried%20figs%20anjeer%20premium%20natural%20sweet?width=400&height=400",
    rating: 4.7,
    reviews: 145,
    badge: "Premium",
    description: "Sweet and chewy dried figs packed with nutrients",
    inStock: true,
    weight: "500g",
    features: ["Sweet", "Chewy", "Nutrient-Rich"],
  },
  {
    id: 72,
    name: "Raisins - Green",
    category: "Dry Fruits & Nuts",
    price: "₹449",
    originalPrice: "₹599",
    image:
      "https://image.pollinations.ai/prompt/green%20raisins%20premium%20natural%20sweet%20dried?width=400&height=400",
    rating: 4.5,
    reviews: 178,
    badge: "Natural",
    description: "Premium green raisins with natural sweetness",
    inStock: true,
    weight: "500g",
    features: ["Natural Sweet", "Premium", "Green"],
  },
  {
    id: 73,
    name: "Brazil Nuts",
    category: "Dry Fruits & Nuts",
    price: "₹1,399",
    originalPrice: "₹1,799",
    image:
      "https://image.pollinations.ai/prompt/brazil%20nuts%20premium%20large%20natural%20healthy?width=400&height=400",
    rating: 4.6,
    reviews: 89,
    badge: "Large",
    description: "Large Brazil nuts rich in selenium and healthy fats",
    inStock: true,
    weight: "500g",
    features: ["Large Size", "Selenium Rich", "Healthy Fats"],
  },
  {
    id: 74,
    name: "Pecans",
    category: "Dry Fruits & Nuts",
    price: "₹1,799",
    originalPrice: "₹2,299",
    image:
      "https://image.pollinations.ai/prompt/pecans%20premium%20nuts%20natural%20healthy%20gourmet?width=400&height=400",
    rating: 4.8,
    reviews: 67,
    badge: "Gourmet",
    description: "Gourmet pecans with rich, buttery flavor",
    inStock: true,
    weight: "500g",
    features: ["Gourmet", "Buttery", "Rich Flavor"],
  },
  {
    id: 75,
    name: "Mixed Dry Fruits",
    category: "Dry Fruits & Nuts",
    price: "₹999",
    originalPrice: "₹1,299",
    image:
      "https://image.pollinations.ai/prompt/mixed%20dry%20fruits%20variety%20pack%20premium%20healthy?width=400&height=400",
    rating: 4.7,
    reviews: 234,
    badge: "Variety",
    description: "Premium mix of assorted dry fruits and nuts",
    inStock: true,
    weight: "500g",
    features: ["Variety Pack", "Assorted", "Premium"],
    discount: 23,
  },
]
